3_url_shortener/tiny_url_poject/project/urls.py
from django.conf.urls import url, patterns, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^url/', include("url.urls", namespace="url")),
]

3_url_shortener/tiny_url_poject/url/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from url import views

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^shorten$', views.UrlShorten.as_view(), name='shorten'),
    url(r'^(?P<key>[A-Za-z0-9\-\_]+)$', views.UrlRedirect.as_view(), name='redirect'),
]

3_url_shortener/tiny_url_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from url_shortener import views
# from url_shortener import views, Index
# from .views import Index


urlpatterns = [
	url(r'^', include('url_shortener.urls', namespace='url_shortener')),
    # url(r'^(?P<key>.+)', views.short_link, name = 'key'),
	# url(r'^url_shortener/', include('url_shortener.urls', namespace='url_shortener')),
    url(r'^admin/', admin.site.urls),
]

3_url_shortener/url_shortener/urls.py
from django.conf.urls import url, include
from .views import Index
from url_shortener import views

urlpatterns = [
	url(r'^url/(?P<key>[0-9a-zA-Z]+)', views.short_link, name='url'),
	url(r'^$', Index.as_view(), name='index'),
]

# (?P<key>[^/]+)

3_url_shortener/tiny_url_poject/url/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone #make sure to set the timezone 
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
import uuid

def url_validation(value):
    # this is a last line check if the client side check let through a non-url value
    # this was taken out of django in v1.5
    if URLValidator():
        raise ValidationError("{} is invalid, try entering in a valid URL".format(value))

class Url(models.Model):
    actual = models.URLField(max_length=120)
    key = models.CharField(max_length=40) # got rid of UUID
    created_at = models.DateTimeField(default = timezone.now,editable=False)
    count = models.IntegerField(default = 0)

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Url, self).save(*args, **kwargs)

    # def clean(self):
    #     url_validation(self.actual)

3_url_shortener/url_shortener/models.py
from django.db import models

# Create your models here.
class Url(models.Model):
	original = models.CharField(max_length=2083)
	short = models.CharField(max_length=500)

	def __str__(self):
		urls = self.original + self.short
		return urls

3_url_shortener/tiny_url_poject/url/forms.py
from django import forms
from .models import Url
# these are already given to us 
from django.contrib.auth.models import User


class UrlForm(forms.ModelForm):
    class Meta:
        model = Url
        fields = [
            "actual",
        ]

3_url_shortener/url_shortener/forms.py
from django import forms
from .models import Url

class UrlForm(forms.ModelForm):
	class Meta:
		model = Url
		fields = [
			'original',
		]

3_url_shortener/tiny_url_poject/url/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import UrlForm
from .models import Url 
import uuid

# Create your views here.
class Index(View):
    def get(self, request):
        return render(request, "url/index.html")

class UrlShorten(View):
    # pu.db
    template = "url/shorten.html"
    def get(self, request):
        form = UrlForm()
        context = {
            'url_form': form,}
        # using self is a fancy way to give a variable name to the template ...?
        return render(request, self.template, context)

    def post(self, request):
        form = UrlForm(data=request.POST)
        # If the forms is valid.
        if form.is_valid():

            form = form.save(commit=False)
            # shorten the UUID to last part 
            key = str(uuid.uuid4()).split('-')[:: -1][0] # REALY NICE!!!
            form.key = key
            form.save()

            new_link = "http://localhost:8000/url/" + str(key)
            url = Url.objects.order_by('-created_at')[0]

            context = {
                'new_link': new_link,
                'url': url,}
            return render(request, "url/index.html", context)

        else:
            context = {
                'url_form': form,}
            return render(request, self.template, context)

class UrlRedirect(View):
    def get(self, request, key=None):
        url = Url.objects.get(key=key)
        website = url.actual
        # print (website)
        return redirect(website)

3_url_shortener/url_shortener/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django.views.generic import View
from url_shortener.forms import UrlForm
from base64 import urlsafe_b64encode
from url_shortener.models import Url
from django.http.response import HttpResponseRedirect
# Create your views here.
class Index(View):
	template = 'url_shortener/index.html'

	def get(self, request):
		context = {
			'forms': UrlForm()
		}
		return render(request, self.template, context)

	def post(self, request):
		if URLValidator(request.POST):
			# take request.POST['original']
			original = request.POST['original']
			# get a key for the url
			# attach original url and key to model
			key = str(urlsafe_b64encode(original.encode('ascii')))[2:12]
			# save to model
			# take key string and concatinate key with localhost stuff
			# pass shortened url back to template
			request.session['key'] = key
			url = Url(original = original, short = key)
			try: 
				Url.objects.get(short = key)
			except Url.DoesNotExist:
				url.save()
			context = {
				'forms': UrlForm(),
				'key': key,
			}
			return render(request, self.template, context)

def short_link(request, key):
	print ('rfhirfrfnrfn')
	# key = 'localhost:8000:' + key
	# foo = get_object_or_404(Url, short=key)
	# print (foo)
	print (key)
	original = Url.objects.get(short=key)
	# original=original.original
	# original = str(original)
	# original.replace(key, '')
	# print (original)
	# original = original
	return HttpResponseRedirect(original)

3_url_shortener/tiny_url_poject/url/templates/url/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>URL Shortener</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/5.5.2/css/foundation.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'url/style.css' %}" />

</head>
<body>

    <h1>URL Shortener</h1>

    <div class=container>
        {% block content %}

        {% endblock content %}
    </div>

</body>
</html>

3_url_shortener/tiny_url_poject/url/templates/url/index.html
{% extends "url/base.html" %}

{% block content %}

    <h2>Welcome Page!</h2>

    <div><a id="shorten" href="/url/shorten"> Shorten Link</a></div>

    <div class='post'>
        <br>
        <p id="title">New URL: </p>
        <a href="{{ new_link }}"> {{ new_link }}</a>
        <br><br>
        <p id="date"> Created at: {{ url.created_at }}</p>
    </div>

{% endblock content %}

3_url_shortener/tiny_url_poject/url/templates/url/shorten.html
{% extends "url/base.html" %}

{% block content %}

    <form action="{% url 'url:shorten' %}" method="POST">
        {% csrf_token %}
            {{url_form.errors }}

<!--             <input type="text" name="actual" value="https://" </input>
 -->
            {% for field in url_form %}
                <div class="{%if field.errors %}error{%endif%}">
                    {{field.label_tag}}{{ field }}
                </div>

                {% if field.help_text %}
                <p> class="help {{ field.help_text|safe }}</p>
                {%endif%}

            {% endfor %}
            
        <input type="submit" class="button" value="Shortanation"/>
    </form>

    <a id="home" href="/url"> Back Home </a>

{% endblock content %}

3_url_shortener/url_shortener/templates/url_shortener/index.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Transformers - Websites in Disguise</title>
	<link rel="stylesheet" href="{% static 'url_shortener/materialize.css' %}">
	<link rel="stylesheet" href="{% static 'url_shortener/main.css' %}">
</head>
<body>
	<h1>Transform your ugly url into a mini-rl!</h1>
	<form action="{% url 'url_shortener:index' %}" method='POST'>
		{% csrf_token %}
		{{ forms.as_p }}
		<input name="submit" type="Submit">
	</form>
	{% if key %}
	<p><a href="{% url 'url_shortener:url' key=key %}">{{ key }}</a></p>
	{%endif%}
</body>
</html>